export default {
  twilight () {
    document.styleSheets[0].insertRule(`pre[class*="language-"] { color: white; background: hsl(0, 0%, 8%); font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace; font-size: 1em; text-align: left; text-shadow: 0 -.1em .2em black; white-space: pre; word-spacing: normal; word-break: normal; word-wrap: normal; line-height: 1.5; -webkit-hyphens: none; -moz-hyphens: none; -ms-hyphens: none; hyphens: none; box-shadow: 1px 1px .5em black inset; }`)
    try { document.styleSheets[0].insertRule(`pre[class*="language-"] ::selection { text-shadow: none; background: hsla(0, 0%, 93%, 0.15); }`) } catch {}
    try { document.styleSheets[0].insertRule(`pre[class*="language-"] ::-moz-selection { text-shadow: none; background: hsla(0, 0%, 93%, 0.15); }`) } catch {}
    try { document.styleSheets[0].insertRule(`pre[class*="language-"]::selection { text-shadow: none; background: hsla(0, 0%, 93%, 0.15); }`) } catch {}
    try { document.styleSheets[0].insertRule(`pre[class*="language-"]::-moz-selection { text-shadow: none; background: hsla(0, 0%, 93%, 0.15); }`) } catch {}
    document.styleSheets[0].insertRule(`.token.comment, .token.prolog, .token.doctype, .token.cdata { color: hsl(0, 0%, 47%); }`)
    document.styleSheets[0].insertRule(`.token.punctuation { opacity: .7; }`)
    document.styleSheets[0].insertRule(`.token.namespace { opacity: .7; }`)
    document.styleSheets[0].insertRule(`.token.tag, .token.boolean, .token.number, .token.deleted { color: hsl(14, 58%, 55%); }`)
    document.styleSheets[0].insertRule(`.token.keyword, .token.property, .token.selector, .token.constant, .token.symbol, .token.builtin { color: hsl(53, 89%, 79%); }`)
    document.styleSheets[0].insertRule(`.token.attr-name, .token.attr-value, .token.string, .token.char, .token.operator, .token.entity, .token.url, .language-css .token.string, .style .token.string, .token.variable, .token.inserted { color: hsl(76, 21%, 52%); }`)
    document.styleSheets[0].insertRule(`.token.atrule { color: hsl(218, 22%, 55%); }`)
    document.styleSheets[0].insertRule(`.token.regex, .token.important { color: hsl(42, 75%, 65%); }`)
    document.styleSheets[0].insertRule(`.token.important, .token.bold { font-weight: bold; }`)
    document.styleSheets[0].insertRule(`.token.italic { font-style: italic; }`)
    document.styleSheets[0].insertRule(`.token.entity { cursor: help; }`)
    document.styleSheets[0].insertRule(`pre[data-line] { padding: 1em 0 1em 3em; position: relative; }`)
    document.styleSheets[0].insertRule(`.language-markup .token.tag, .language-markup .token.attr-name, .language-markup .token.punctuation { color: hsl(33, 33%, 52%); }`)
    document.styleSheets[0].insertRule(`.token { position: relative; z-index: 1; }`)
    document.styleSheets[0].insertRule(`.line-highlight { background: hsla(0, 0%, 33%, 0.25); background: linear-gradient(to right, hsla(0, 0%, 33%, .1) 70%, hsla(0, 0%, 33%, 0)); border-bottom: 1px dashed hsl(0, 0%, 33%); border-top: 1px dashed hsl(0, 0%, 33%); left: 0; line-height: inherit; margin-top: 0.75em; padding: inherit 0; pointer-events: none; position: absolute; right: 0; white-space: pre; z-index: 0; }`)
    document.styleSheets[0].insertRule(`.line-highlight:before, .line-highlight[data-end]:after { background-color: hsl(215, 15%, 59%); border-radius: 999px; box-shadow: 0 1px white; color: hsl(24, 20%, 95%); content: attr(data-start); font: bold 65%/1.5 sans-serif; left: .6em; min-width: 1em; padding: 0 .5em; position: absolute; text-align: center; text-shadow: none; top: .4em; vertical-align: .3em; }`)
    document.styleSheets[0].insertRule(`.line-highlight[data-end]:after { bottom: .4em; content: attr(data-end); top: auto; }`)
  },
  tomorrow () {
    document.styleSheets[0].insertRule(`pre[class*="language-"] { color: #ccc; background: #2d2d2d; font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace; font-size: 1em; text-align: left; white-space: pre; word-spacing: normal; word-break: normal; word-wrap: normal; line-height: 1.5; -webkit-hyphens: none; -moz-hyphens: none; -ms-hyphens: none; hyphens: none; }`)
    document.styleSheets[0].insertRule(`.token.comment, .token.block-comment, .token.prolog, .token.doctype, .token.cdata { color: #999; }`)
    document.styleSheets[0].insertRule(`.token.punctuation { color: #ccc; }`)
    document.styleSheets[0].insertRule(`.token.tag, .token.attr-name, .token.namespace, .token.deleted { color: #e2777a; }`)
    document.styleSheets[0].insertRule(`.token.function-name { color: #6196cc; }`)
    document.styleSheets[0].insertRule(`.token.boolean, .token.number, .token.function { color: #f08d49; }`)
    document.styleSheets[0].insertRule(`.token.property, .token.class-name, .token.constant, .token.symbol { color: #f8c555; }`)
    document.styleSheets[0].insertRule(`.token.selector, .token.important, .token.atrule, .token.keyword, .token.builtin { color: #cc99cd; }`)
    document.styleSheets[0].insertRule(`.token.string, .token.char, .token.attr-value, .token.regex, .token.variable { color: #7ec699; }`)
    document.styleSheets[0].insertRule(`.token.operator, .token.entity, .token.url { color: #67cdcc; }`)
    document.styleSheets[0].insertRule(`.token.important, .token.bold { font-weight: bold; }`)
    document.styleSheets[0].insertRule(`.token.italic { font-style: italic; }`)
    document.styleSheets[0].insertRule(`.token.entity { cursor: help; }`)
    document.styleSheets[0].insertRule(`.token.inserted { color: green; }`)
  },
  solarizedlight () {
    document.styleSheets[0].insertRule(`pre[class*="language-"] { color: #657b83; font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace; font-size: 1em; text-align: left; white-space: pre; word-spacing: normal; word-break: normal; word-wrap: normal; line-height: 1.5; -webkit-hyphens: none; -moz-hyphens: none; -ms-hyphens: none; hyphens: none; background: #fdf6e3; }`)
    try { document.styleSheets[0].insertRule(`pre[class*="language-"] ::selection { background: #073642; }`) } catch {}
    try { document.styleSheets[0].insertRule(`pre[class*="language-"] ::-moz-selection { background: #073642; }`) } catch {}
    try { document.styleSheets[0].insertRule(`pre[class*="language-"]::selection { background: #073642; }`) } catch {}
    try { document.styleSheets[0].insertRule(`pre[class*="language-"]::-moz-selection { background: #073642; }`) } catch {}
    document.styleSheets[0].insertRule(`.token.comment, .token.prolog, .token.doctype, .token.cdata { color: #93a1a1; }`)
    document.styleSheets[0].insertRule(`.token.punctuation { color: #586e75; }`)
    document.styleSheets[0].insertRule(`.token.namespace { opacity: .7; }`)
    document.styleSheets[0].insertRule(`.token.property, .token.tag, .token.boolean, .token.number, .token.constant, .token.symbol, .token.deleted { color: #268bd2; }`)
    document.styleSheets[0].insertRule(`.token.selector, .token.attr-name, .token.string, .token.char, .token.builtin, .token.url, .token.inserted { color: #2aa198; }`)
    document.styleSheets[0].insertRule(`.token.entity { color: #657b83; background: #eee8d5; }`)
    document.styleSheets[0].insertRule(`.token.atrule, .token.attr-value, .token.keyword { color: #859900; }`)
    document.styleSheets[0].insertRule(`.token.function, .token.class-name { color: #b58900; }`)
    document.styleSheets[0].insertRule(`.token.regex, .token.important, .token.variable { color: #cb4b16; }`)
    document.styleSheets[0].insertRule(`.token.important, .token.bold { font-weight: bold; }`)
    document.styleSheets[0].insertRule(`.token.italic { font-style: italic; }`)
    document.styleSheets[0].insertRule(`.token.entity { cursor: help; }`)
  },
  okaidia () {
    document.styleSheets[0].insertRule(`pre[class*="language-"] { color: #f8f8f2; text-shadow: 0 1px rgba(0, 0, 0, 0.3); font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace; font-size: 1em; text-align: left; white-space: pre; word-spacing: normal; word-break: normal; word-wrap: normal; line-height: 1.5; -webkit-hyphens: none; -moz-hyphens: none; -ms-hyphens: none; hyphens: none; background: #272822; }`)
    document.styleSheets[0].insertRule(`.token.comment, .token.prolog, .token.doctype, .token.cdata { color: #8292a2; }`)
    document.styleSheets[0].insertRule(`.token.punctuation { color: #f8f8f2; }`)
    document.styleSheets[0].insertRule(`.token.namespace { opacity: .7; }`)
    document.styleSheets[0].insertRule(`.token.property, .token.tag, .token.constant, .token.symbol, .token.deleted { color: #f92672; }`)
    document.styleSheets[0].insertRule(`.token.boolean, .token.number { color: #ae81ff; }`)
    document.styleSheets[0].insertRule(`.token.selector, .token.attr-name, .token.string, .token.char, .token.builtin, .token.inserted { color: #a6e22e; }`)
    document.styleSheets[0].insertRule(`.token.operator, .token.entity, .token.url, .language-css .token.string, .style .token.string, .token.variable { color: #f8f8f2; }`)
    document.styleSheets[0].insertRule(`.token.atrule, .token.attr-value, .token.function, .token.class-name { color: #e6db74; }`)
    document.styleSheets[0].insertRule(`.token.keyword { color: #66d9ef; }`)
    document.styleSheets[0].insertRule(`.token.regex, .token.important { color: #fd971f; }`)
    document.styleSheets[0].insertRule(`.token.important, .token.bold { font-weight: bold; }`)
    document.styleSheets[0].insertRule(`.token.italic { font-style: italic; }`)
    document.styleSheets[0].insertRule(`.token.entity { cursor: help; }`)
  },
  funky () {
    document.styleSheets[0].insertRule(`pre[class*="language-"] { font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace; font-size: 1em; text-align: left; white-space: pre; word-spacing: normal; word-break: normal; word-wrap: normal; line-height: 1.5; -webkit-hyphens: none; -moz-hyphens: none; -ms-hyphens: none; hyphens: none; background: url('data:image/svg+xml;charset=utf-8,<svg%20version%3D"1.1"%20xmlns%3D"http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg"%20width%3D"100"%20height%3D"100"%20fill%3D"rgba(0%2C0%2C0%2C.05)">%0D%0A<polygon%20points%3D"0%2C50%2050%2C0%200%2C0"%20%2F>%0D%0A<polygon%20points%3D"0%2C100%2050%2C100%20100%2C50%20100%2C0"%20%2F>%0D%0A<%2Fsvg>'); background-size: 1em 1em; }`)
    document.styleSheets[0].insertRule(`.token.comment, .token.prolog, .token.doctype, .token.cdata { color: #aaa; }`)
    document.styleSheets[0].insertRule(`.token.punctuation { color: #999; }`)
    document.styleSheets[0].insertRule(`.token.namespace { opacity: .7; }`)
    document.styleSheets[0].insertRule(`.token.property, .token.tag, .token.boolean, .token.number, .token.constant, .token.symbol { color: #0cf; }`)
    document.styleSheets[0].insertRule(`.token.selector, .token.attr-name, .token.string, .token.char, .token.builtin { color: yellow; }`)
    document.styleSheets[0].insertRule(`.token.operator, .token.entity, .token.url, .language-css .token.string, .token.variable, .token.inserted { color: yellowgreen; }`)
    document.styleSheets[0].insertRule(`.token.atrule, .token.attr-value, .token.keyword { color: deeppink; }`)
    document.styleSheets[0].insertRule(`.token.regex, .token.important { color: orange; }`)
    document.styleSheets[0].insertRule(`.token.important, .token.bold { font-weight: bold; }`)
    document.styleSheets[0].insertRule(`.token.italic { font-style: italic; }`)
    document.styleSheets[0].insertRule(`.token.entity { cursor: help; }`)
    document.styleSheets[0].insertRule(`.token.deleted { color: red; }`)
    document.styleSheets[0].insertRule(`pre.diff-highlight.diff-highlight > code .token.deleted:not(.prefix), pre > code.diff-highlight.diff-highlight .token.deleted:not(.prefix) { background-color: rgba(255, 0, 0, .3); display: inline; }`)
    document.styleSheets[0].insertRule(`pre.diff-highlight.diff-highlight > code .token.inserted:not(.prefix), pre > code.diff-highlight.diff-highlight .token.inserted:not(.prefix) { background-color: rgba(0, 255, 128, .3); display: inline; }`)
  },
  dark () {
    document.styleSheets[0].insertRule(`pre[class*="language-"] { color: white; text-shadow: 0 -.1em .2em black; font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace; font-size: 1em; text-align: left; white-space: pre; word-spacing: normal; word-break: normal; word-wrap: normal; line-height: 1.5; -webkit-hyphens: none; -moz-hyphens: none; -ms-hyphens: none; hyphens: none; background: hsl(30, 20%, 25%); box-shadow: 1px 1px .5em black inset; }`)
    document.styleSheets[0].insertRule(`@media print { pre[class*="language-"] { text-shadow: none; } }`)
    document.styleSheets[0].insertRule(`.token.comment, .token.prolog, .token.doctype, .token.cdata { color: hsl(30, 20%, 50%); }`)
    document.styleSheets[0].insertRule(`.token.punctuation { opacity: .7; }`)
    document.styleSheets[0].insertRule(`.token.namespace { opacity: .7; }`)
    document.styleSheets[0].insertRule(`.token.property, .token.tag, .token.boolean, .token.number, .token.constant, .token.symbol { color: hsl(350, 40%, 70%); }`)
    document.styleSheets[0].insertRule(`.token.selector, .token.attr-name, .token.string, .token.char, .token.builtin, .token.inserted { color: hsl(75, 70%, 60%); }`)
    document.styleSheets[0].insertRule(`.token.operator, .token.entity, .token.url, .language-css .token.string, .style .token.string, .token.variable { color: hsl(40, 90%, 60%); }`)
    document.styleSheets[0].insertRule(`.token.atrule, .token.attr-value, .token.keyword { color: hsl(350, 40%, 70%); }`)
    document.styleSheets[0].insertRule(`.token.regex, .token.important { color: #e90; } `)
    document.styleSheets[0].insertRule(`.token.important, .token.bold { font-weight: bold; }`)
    document.styleSheets[0].insertRule(`.token.italic { font-style: italic; }`)
    document.styleSheets[0].insertRule(`.token.entity { cursor: help; }`)
    document.styleSheets[0].insertRule(`.token.deleted { color: red; }`)
  },
  coy () {
    document.styleSheets[0].insertRule(`pre[class*="language-"] { color: black; font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace; font-size: 1em; text-align: left; white-space: pre; word-spacing: normal; word-break: normal; word-wrap: normal; line-height: 1.5; -webkit-hyphens: none; -moz-hyphens: none; -ms-hyphens: none; hyphens: none; position: relative; background: #fdfdfd; }`)
    document.styleSheets[0].insertRule(`.token.comment, .token.block-comment, .token.prolog, .token.doctype, .token.cdata { color: #7D8B99; }`)
    document.styleSheets[0].insertRule(`.token.punctuation { color: #5F6364; }`)
    document.styleSheets[0].insertRule(`.token.property, .token.tag, .token.boolean, .token.number, .token.function-name, .token.constant, .token.symbol, .token.deleted { color: #c92c2c; }`)
    document.styleSheets[0].insertRule(`.token.selector, .token.attr-name, .token.string, .token.char, .token.function, .token.builtin, .token.inserted { color: #2f9c0a; }`)
    document.styleSheets[0].insertRule(`.token.operator, .token.entity, .token.url, .token.variable { color: #a67f59; background: rgba(255, 255, 255, 0.5); }`)
    document.styleSheets[0].insertRule(`.token.atrule, .token.attr-value, .token.keyword, .token.class-name { color: #1990b8; }`)
    document.styleSheets[0].insertRule(`.token.regex, .token.important { color: #e90; }`)
    document.styleSheets[0].insertRule(`.language-css .token.string, .style .token.string { color: #a67f59; background: rgba(255, 255, 255, 0.5); }`)
    document.styleSheets[0].insertRule(`.token.important { font-weight: normal; }`)
    document.styleSheets[0].insertRule(`.token.bold { font-weight: bold; }`)
    document.styleSheets[0].insertRule(`.token.italic { font-style: italic; }`)
    document.styleSheets[0].insertRule(`.token.entity { cursor: help; }`)
    document.styleSheets[0].insertRule(`.token.namespace { opacity: .7; }`)
    document.styleSheets[0].insertRule(`pre[class*="language-"].line-numbers.line-numbers { padding-left: 0; }`)
    document.styleSheets[0].insertRule(`pre[class*="language-"].line-numbers.line-numbers code { padding-left: 3.8em; }`)
    document.styleSheets[0].insertRule(`pre[class*="language-"].line-numbers.line-numbers .line-numbers-rows { left: 0; }`)
    document.styleSheets[0].insertRule(`pre[class*="language-"][data-line] { padding-top: 0; padding-bottom: 0; padding-left: 0; }`)
    document.styleSheets[0].insertRule(`pre[data-line] code { position: relative; padding-left: 4em; }`)
    document.styleSheets[0].insertRule(`pre .line-highlight { margin-top: 0; }`)
  },
  default () {
    document.styleSheets[0].insertRule(`pre[class*="language-"] { color: black; background: #f5f2f0; text-shadow: 0 1px white; font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace; font-size: 1em; text-align: left; white-space: pre; word-spacing: normal; word-break: normal; word-wrap: normal; line-height: 1.5; -moz-tab-size: 4; -o-tab-size: 4; tab-size: 4; -webkit-hyphens: none; -moz-hyphens: none; -ms-hyphens: none; hyphens: none; }`)
    try { document.styleSheets[0].insertRule(`pre[class*="language-"] ::selection { text-shadow: none; background: #b3d4fc; }`) } catch {}
    try { document.styleSheets[0].insertRule(`pre[class*="language-"] ::-moz-selection { text-shadow: none; background: #b3d4fc; }`) } catch {}
    try { document.styleSheets[0].insertRule(`pre[class*="language-"]::selection { text-shadow: none; background: #b3d4fc; }`) } catch {}
    try { document.styleSheets[0].insertRule(`pre[class*="language-"]::-moz-selection { text-shadow: none; background: #b3d4fc; }`) } catch {}
    document.styleSheets[0].insertRule(`@media print { pre[class*="language-"] { text-shadow: none; } }`)
    document.styleSheets[0].insertRule(`.token.comment, .token.prolog, .token.doctype, .token.cdata { color: slategray; }`)
    document.styleSheets[0].insertRule(`.token.punctuation { color: #999; }`)
    document.styleSheets[0].insertRule(`.token.namespace { opacity: .7; }`)
    document.styleSheets[0].insertRule(`.token.property, .token.tag, .token.boolean, .token.number, .token.constant, .token.symbol, .token.deleted { color: #905; }`)
    document.styleSheets[0].insertRule(`.token.selector, .token.attr-name, .token.string, .token.char, .token.builtin, .token.inserted { color: #690; }`)
    document.styleSheets[0].insertRule(`.token.operator, .token.entity, .token.url, .language-css .token.string, .style .token.string { color: #9a6e3a; background: hsla(0, 0%, 100%, .5); }`)
    document.styleSheets[0].insertRule(`.token.atrule, .token.attr-value, .token.keyword { color: #07a; }`)
    document.styleSheets[0].insertRule(`.token.function, .token.class-name { color: #DD4A68; }`)
    document.styleSheets[0].insertRule(`.token.regex, .token.important, .token.variable { color: #e90; }`)
    document.styleSheets[0].insertRule(`.token.important, .token.bold { font-weight: bold; }`)
    document.styleSheets[0].insertRule(`.token.italic { font-style: italic; }`)
    document.styleSheets[0].insertRule(`.token.entity { cursor: help; }`)
  },
  public () {
    document.styleSheets[0].insertRule(`pre[class*="language-"] { border-radius: none !important; padding: 0 0 1rem 1rem !important; margin: 3px 0 0 0 !important; overflow: auto !important; -webkit-box-sizing: content-box !important; -moz-box-sizing: content-box !important; box-sizing: content-box !important; border: none !important; }`)
    document.styleSheets[0].insertRule(`._um-_note-container { min-width: 260px; overflow: hidden; border-radius: 3px; transition: .3s; position: relative; }`)
    document.styleSheets[0].insertRule(`._um-_note-headbox { width: 100%; height: 16px; transition: .3s; overflow: hidden; position: relative; z-index: 100; }`)
    document.styleSheets[0].insertRule(`._um-_unfold-box { height: 30px; font-size: 10px; display: inline-block; cursor: pointer; zoom: .75; position: absolute; left: 5px; top: -3px; }`)
    document.styleSheets[0].insertRule(`._um-_unfold-text { display: inline-block; transition: .3s; position: absolute; top: 4px; }`)
    document.styleSheets[0].insertRule(`._um-_unflod-arrow { display: inline-block; zoom: 1.3; transform-origin: left center; transition: .3s; position: absolute; top: 1px; }`)
    document.styleSheets[0].insertRule(`._um-_note-config-edit { width: 10px; height: 10px; border-radius: 50%; cursor: pointer; float: right; margin-right: 3px; margin-top: 3px; }`)
    document.styleSheets[0].insertRule(`._um-_note-config-submit { width: 10px; height: 10px; border-radius: 50%; cursor: pointer; background: orange; float: right; margin-right: 3px; margin-top: 3px; }`)
    document.styleSheets[0].insertRule(`._um-_submit-confirm { height: 12px; margin-top: 2px; margin-right: 5px; padding: 0 2px; border-radius: 2px; overflow: hidden; float: right; position: relative; z-index: 10; }`)
    document.styleSheets[0].insertRule(`._um-_submit-item-cancel,._um-_submit-item-ok { width: 20px; height: 12px; line-height: 12px; text-align: center; border-radius: 6px; font-size: 12px; display: inline-block; margin: 0 4px; cursor: pointer; position: relative; top: -4px; }`)
    document.styleSheets[0].insertRule(`._um-submit-span { position: relative; top: -1px; }`)
    document.styleSheets[0].insertRule(`._um-_pre-class { min-width: calc(260px - 1rem); position: relative; }`)
    document.styleSheets[0].insertRule(`._um-_not-chooseable { user-select: none; -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; }`)
    document.styleSheets[0].insertRule(`._um-_code-box { position: relative; }`)
    document.styleSheets[0].insertRule(`._um-_sign-public { font-size: 10px; position: absolute; }`)
    document.styleSheets[0].insertRule(`._um-_line-dashed { position: absolute; }`)
    document.styleSheets[0].insertRule(`._um-_sign-add { width: 16px; height: 18px; line-height: 16px; text-align: center; cursor: pointer; font-size: 18px; position: absolute; }`)
    document.styleSheets[0].insertRule(`._um-_sign-minus { width: 12px; height: 18px; transform: scale(1.3, 1); line-height: 16px; text-align: center; cursor: pointer; font-size: 18px; position: absolute; }`)
    document.styleSheets[0].insertRule(`._um-_select-container { max-width: calc(100% - 40px); box-shadow: 3px 3px 7px rgba(0, 0, 0, .3); padding: 2px; position: absolute; z-index: 10; }`)
    document.styleSheets[0].insertRule(`._um-_select-item { line-height: 20px; padding: 0 5px; margin: 2px; cursor: pointer; border-radius: 3px; float: left; }`)
    document.styleSheets[0].insertRule(`._um-_confirm-container { padding: 2px; box-shadow: 3px 3px 7px rgba(0, 0, 0, .3); position: absolute; z-index: 10; }`)
    document.styleSheets[0].insertRule(`._um-_confirm-message { font-size: 10px; padding: 2px 2px 4px 2px; }`)
    document.styleSheets[0].insertRule(`._um-_confirm-item { line-height: 20px; font-size: 12px; padding: 2px 10px; margin: 2px; cursor: pointer; border-radius: 3px; float: left; }`)
    document.styleSheets[0].insertRule(`._um-_code-class { min-width: calc(100% - 1rem); display: inline-block; padding-right: 1rem; outline: none; margin: 20px 0 30px 0; }`)
  },
}
